# Generated by Django 6.0.1 on 2026-01-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='company',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['profile', 'name'], name='idx_skill_profile_name'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['profile', 'title'], name='idx_project_profile_title'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['profile', 'start_date'], name='idx_work_profile_start'),
        ),
    ]
